"""initial schema

Revision ID: da9200ff25a4
Revises: 
Create Date: 2026-09-27 09:59:21.199743

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'da9200ff25a4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_account_type'), 'accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_accounts_external_id'), 'accounts', ['external_id'], unique=True)
    op.create_index(op.f('ix_accounts_risk_level'), 'accounts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_accounts_status'), 'accounts', ['status'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_external_id'), 'devices', ['external_id'], unique=True)
    op.create_index(op.f('ix_devices_risk_level'), 'devices', ['risk_level'], unique=False)
    op.create_table('ip_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=45), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_addresses_address'), 'ip_addresses', ['address'], unique=True)
    op.create_index(op.f('ix_ip_addresses_risk_level'), 'ip_addresses', ['risk_level'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('recipient_account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('ip_address_id', sa.Integer(), nullable=True),
    sa.Column('is_new_device', sa.Boolean(), nullable=False),
    sa.Column('is_new_ip', sa.Boolean(), nullable=False),
    sa.Column('txn_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ip_address_id'], ['ip_addresses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index('ix_transactions_account_timestamp', 'transactions', ['account_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_device_id'), 'transactions', ['device_id'], unique=False)
    op.create_index(op.f('ix_transactions_external_id'), 'transactions', ['external_id'], unique=True)
    op.create_index(op.f('ix_transactions_ip_address_id'), 'transactions', ['ip_address_id'], unique=False)
    op.create_index(op.f('ix_transactions_recipient_account_id'), 'transactions', ['recipient_account_id'], unique=False)
    op.create_index('ix_transactions_recipient_timestamp', 'transactions', ['recipient_account_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_timestamp'), 'transactions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('risk_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_external_id'), 'alerts', ['external_id'], unique=True)
    op.create_index(op.f('ix_alerts_risk_level'), 'alerts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index('ix_alerts_status_level', 'alerts', ['status', 'risk_level'], unique=False)
    op.create_index(op.f('ix_alerts_transaction_id'), 'alerts', ['transaction_id'], unique=False)
    op.create_table('investigation_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('assigned_to', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_cases_alert_id'), 'investigation_cases', ['alert_id'], unique=False)
    op.create_index(op.f('ix_investigation_cases_external_id'), 'investigation_cases', ['external_id'], unique=True)
    op.create_index(op.f('ix_investigation_cases_severity'), 'investigation_cases', ['severity'], unique=False)
    op.create_index(op.f('ix_investigation_cases_status'), 'investigation_cases', ['status'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['investigation_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'source', 'source_reference', name='uq_evidence_case_source_ref')
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_type'), 'evidence', ['evidence_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_evidence_type'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_investigation_cases_status'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_severity'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_external_id'), table_name='investigation_cases')
    op.drop_index(op.f('ix_investigation_cases_alert_id'), table_name='investigation_cases')
    op.drop_table('investigation_cases')
    op.drop_index(op.f('ix_alerts_transaction_id'), table_name='alerts')
    op.drop_index('ix_alerts_status_level', table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_risk_level'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_external_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_timestamp'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index('ix_transactions_recipient_timestamp', table_name='transactions')
    op.drop_index(op.f('ix_transactions_recipient_account_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_ip_address_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_external_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_device_id'), table_name='transactions')
    op.drop_index('ix_transactions_account_timestamp', table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_ip_addresses_risk_level'), table_name='ip_addresses')
    op.drop_index(op.f('ix_ip_addresses_address'), table_name='ip_addresses')
    op.drop_table('ip_addresses')
    op.drop_index(op.f('ix_devices_risk_level'), table_name='devices')
    op.drop_index(op.f('ix_devices_external_id'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_accounts_status'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_risk_level'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_external_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_account_type'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
